services:
  python-bot:
    restart: always
    build: .
    volumes:
      - ./logs:/var/log
      #- /src/bot_get_issues:/opt/bot_get_issues
      - /data:/data
    environment:
      - REDIS_HOST=redis
      - REDIS_PORT=6379
    depends_on:
      - redis

  redis:
    image: redis:latest
    command: [ "redis-server", "--appendonly", "yes", "--bind", "0.0.0.0" ]
    ports:
      - "6379:6379"
    volumes:
      - redis-data:/data

volumes:
  redis-data:
