services:
  python-bot:
    restart: always
    build: .
    volumes:
      - ./logs:/var/log
#      - /src/bot_get_issues:/opt/bot_get_issues  # на хосте в src хранится проект с гит
    networks:
      - my_network
    environment:
      - REDIS_HOST=redis
      - REDIS_PORT=6379
    depends_on:
       redis:
          condition: service_healthy

  redis:
    image: redis:latest
    command: [ "redis-server", "--appendonly", "yes", "--bind", "0.0.0.0", "--requirepass", "Prodam_Garaj_8-963-852-74-10"]
    networks:
      - my_network
    healthcheck:
      test: [ "CMD", "redis-cli", "ping" ]
      interval: 10s
      timeout: 5s
      retries: 5
    volumes:
      - redis-data:/data  # "Mountpoint": "/var/lib/docker/volumes/bot_get_issues_redis-data/_data"

volumes:
  redis-data:

networks:
  my_network:
