version: 1
disable_existing_loggers: True

formatters:
  default:
    format: '[%(asctime)s] #%(levelname)-8s %(filename)s:%(lineno)d - %(name)s:%(funcName)s - %(message)s'

handlers:
  default:
    class: logging.StreamHandler
    formatter: default
    level: ERROR

  stdout:
    class: logging.StreamHandler
    formatter: default
    level: DEBUG
    stream: ext://sys.stdout

  error_file:
    class: logging.FileHandler
    filename: bot_get_issues/logs/bot_logs.log
    mode: w
    level: DEBUG
    formatter: default

loggers:
  bot_get_issues.run_bot:
    level: INFO
    handlers: [stdout, error_file]

  bot_get_issues.logic.cli:
    level: DEBUG
    handlers: [stdout, error_file]

  bot_get_issues.logic.database:
    level: DEBUG
    handlers: [stdout, error_file]

root:
  formatter: default
  handlers: [default]